In [1]:
import numpy as np

y = np.array([3+4j, 0.4+7.8j])
print(y.dtype)

**Python**

In [7]:
import numpy as np

x = np.arange(90).reshape(3, 15, 2)
print(x)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]
  [10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]
  [20 21]
  [22 23]
  [24 25]
  [26 27]
  [28 29]]

 [[30 31]
  [32 33]
  [34 35]
  [36 37]
  [38 39]
  [40 41]
  [42 43]
  [44 45]
  [46 47]
  [48 49]
  [50 51]
  [52 53]
  [54 55]
  [56 57]
  [58 59]]

 [[60 61]
  [62 63]
  [64 65]
  [66 67]
  [68 69]
  [70 71]
  [72 73]
  [74 75]
  [76 77]
  [78 79]
  [80 81]
  [82 83]
  [84 85]
  [86 87]
  [88 89]]]


* code


+ code

- Code

In [4]:
%history

%history
%history
%histories
%history


In [8]:
import numpy as np

x = np.arange(20).reshape(4, 5)

print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [9]:
import numpy as np

print(np.repeat(3, 4))

[3 3 3 3]


In [10]:
import numpy as np

x = np.arange(20).reshape(4,5)
print(x.mean(axis=1))

[ 2.  7. 12. 17.]


In [11]:
import numpy as np

x = np.array([[-2], 
              [2]])
y = np.array([[-3, 3]])
print(x.dot(y))

[[ 6 -6]
 [-6  6]]


In [23]:
import numpy as np
y = np.array([[0, 1, 2],
              [3, 4, 5]])

print('slice 1 \n')
print(y[1:3, 1:4]) 

print('\n slice 2 \n')
print(y[1])   

print('\n slice 3 \n')
print(y[:, 1]) 

slice 1 

[[4 5]]

 slice 2 

[3 4 5]

 slice 3 

[1 4]


In [24]:
import numpy as np

x = np.arange(30).reshape(3,5,2)
print(x[1,::2,1])

[11 15 19]


In [25]:
import numpy as np

x = np.arange(30).reshape(3,5,2)
print(x[-1, 2:-1, -1])

[25 27]


In [26]:
import numpy as np

x = np.arange(12).reshape(3,4)
print(x[-2])

[4 5 6 7]


In [27]:
import numpy as np

x = np.arange(12).reshape(3,4)
print(x[-1:,].shape)

(1, 4)


In [28]:
import numpy as np

x = np.arange(12).reshape(3,4)
print(x[:,1])

[1 5 9]


In [29]:
import numpy as np

x = np.arange(12).reshape(3,4)
print(x[:,1])

[1 5 9]


In [30]:
import numpy as np

x = np.arange(30).reshape(3,5,2)
print(x[1,::2,1])

[11 15 19]


In [31]:
import numpy as np

x = np.arange(4).reshape(2,2)

y = np.vsplit(x,2)
print(y[0])

[[0 1]]


In [32]:
import numpy as np

x = np.arange(30).reshape(5,6)
print(x.argmax(axis=1))

[5 5 5 5 5]


In [33]:
import numpy as np

x = np.arange(4)
print(x**2)

[0 1 4 9]


In [34]:
import numpy as np

x = np.arange(4)
y = np.arange(4)

print(x == y)


[ True  True  True  True]


In [35]:
import numpy as np

x = np.arange(20).reshape(4,5)
print(x.mean(axis=1))

[ 2.  7. 12. 17.]


In [36]:
import numpy as np

y = np.array([3+4j, 0.4+7.8j])
print(y.dtype)

complex128


In [37]:
import numpy as np

x = np.array([[1, 2], [3, 4], [5, 6]])
print(x[[0, 1, 2], [0, 1, 1]])

[1 4 6]


In [38]:
import numpy as np

x = np.arange(4)
print(x.flatten())

[0 1 2 3]


In [39]:
import numpy as np

x = np.array([[-1,0,1], [-2, 0, 2]])

y = np.zeros_like(x)
print(y)

[[0 0 0]
 [0 0 0]]


In [42]:
import numpy as np

x = np.arange(20).reshape(4, 5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [43]:
import numpy as np

x = np.array([[0, 1], [1, 1], [2, 2]])
print(x.sum(-1))

[1 2 4]
